function a(a) {
    for (var t = new Date().getMonth() + 1, r = 0; r < a.length; r++) {
        if (a[r].north.includes("全年")) a[r].northTimeStatus = 0; else {
            var m = a[r].north;
            a[r].northTimeStatus = e(t, m);
        }
        if (a[r].south.includes("全年")) a[r].southTimeStatus = 0; else {
            var n = a[r].south;
            a[r].southTimeStatus = e(t, n);
        }
    }
    return a;
}

function e(a, e) {
    if (e.includes("、")) {
        var r = e.split("、"), m = t(a, r[0]), n = t(a, r[1]);
        return Math.max(m, n);
    }
    return t(a, e);
}

function t(a, e) {
    if (e.includes("-")) {
        var t = e.split("-"), r = [ parseInt(t[0]), parseInt(t[1]) ];
        if (t[0] = r[0], t[1] = r[1], t[0] - 1 == a) return 1;
        if (t[1] == a) return 2;
    } else {
        var m = parseInt(e);
        if (m - 1 == a) return 1;
        if (m == a) return 2;
    }
    return 0;
}

Object.defineProperty(exports, "__esModule", {
    value: !0
}), exports.getFishs = function() {
    return a(r);
}, exports.getInsects = function() {
    return a(m);
};

exports.residents = [ 
{
    image:'https://img.moegirl.org/common/1/1d/Pecoriinu.png',
    race: "前卫",
    nature: "一星",
    sex: "♀",
    name: "佩可莉姆",
    option_name:"peikelimu",
    motto: "只要你露出笑容的话，我也会忍不住微笑!",
    tag: "M·A·O",
    skill1_name:"公主之力",
    skill1_des:"战斗开始时,中幅提升自身最大生命力",
    skill1_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/01/02/icon-1.png",
    skill2_name:"沉重一击",
    skill2_des:"对前方一名敌人造成物理伤害(中)",
    skill2_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/01/02/icon-2.png",
    skill3_name:"午餐时间",
    skill3_des:"小幅提升自身的魔法防御力,并小幅回复生命值",
    skill3_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/01/02/icon-3.png",
    skill4_name:"公主突袭",
    skill4_des:"对前方一名敌人造成物理伤害(大),并中幅提升自身的物理与魔法防御力",
    skill4_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/01/02/icon-4.png",
    skill4_gif:"//static.biligame.com/pcr/gw/pc/images/p4/clan/01/02/4.gif",
}, {
    image:"https://img.moegirl.org/common/2/22/Coccoro.png",
    race: "中卫",
    nature: "一星",
    sex: "♀",
    name: "可可萝",
    option_name:"kekeluo",
    motto: "我会献上我的全部来守护主人",
    tag: "伊藤美来",
    skill1_name:"精灵的启示",
    skill1_des:"战斗开始时中幅度提升自身物攻",
    skill1_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/01/03/icon-1.png",
    skill2_name:"加速",
    skill2_des:"小幅提升己方全体的行动速度、物理攻击力",
    skill2_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/01/03/icon-2.png",
    skill3_name:"掠阵三段击",
    skill3_des:"对前方一名敌人造成物理伤害(中)",
    skill3_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/01/03/icon-3.png",
    skill4_name:"极光",
    skill4_des:"小幅提升己方全体的物理、魔法攻击力,并小幅回复自身生命",
    skill4_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/01/03/icon-4.png",
    skill4_gif:"//static.biligame.com/pcr/gw/pc/images/p4/clan/01/03/4.gif",
}, {
    image:"https://img.moegirl.org/common/0/0c/Kyaru.png",
    race: "后卫",
    nature: "一星",
    sex: "♀",
    name: "凯露",
    option_name:"kailu",
    motto: "尽情来夸奖我也是可以的噢!",
    tag: "立花理香",
    skill1_name:"黑暗之蚀",
    skill1_des:"战斗开始时中幅度提升自己的魔攻",
    skill1_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/01/01/icon-1.png",
    skill2_name:"护甲削弱",
    skill2_des:"小幅降低前方一名敌人的物理、魔法防御力",
    skill2_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/01/01/icon-2.png",
    skill3_name:"闪电球",
    skill3_des:"对前方一名敌人造成魔法伤害(中)",
    skill3_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/01/01/icon-3.png",
    skill4_name:"格林炸裂",
    skill4_des:"对敌方全体造成魔法伤害(中)",
    skill4_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/01/01/icon-4.png",
    skill4_gif:"//static.biligame.com/pcr/gw/pc/images/p4/clan/01/01/4.gif",
}, {
    image:"https://img.moegirl.org/common/5/54/Hiyori_prin_cone.png",
    race: "前卫",
    nature: "一星",
    sex: "♀",
    name: "日和莉",
    option_name:"riheli",
    motto: "我要变得更强,去帮助那些正在困扰的人们!",
    tag: "东山奈央",
    skill1_name:"肉球力量",
    skill1_des:"战斗开始时中幅度提升自己的物攻",
    skill1_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/02/01/icon-1.png",
    skill2_name:"猫咪组合拳",
    skill2_des:"对前方一名敌人造成物理伤害(小),并中幅提升自身物理攻击力",
    skill2_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/02/01/icon-2.png",
    skill3_name:"猫咪重击",
    skill3_des:"对前方一名敌人造成物理伤害(中)",
    skill3_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/02/01/icon-3.png",
    skill4_name:"日和莉突击",
    skill4_des:"对前方一名敌人造成物理伤害(大),并对其小范围内的所有敌人造成物理伤害(中)",
    skill4_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/02/01/icon-4.png",
    skill4_gif:"//static.biligame.com/pcr/gw/pc/images/p4/clan/02/01/4.gif",
}, {
    image:"https://img.moegirl.org/common/0/01/Yui_prin_cone.png",
    race: "后卫",
    nature: "一星",
    sex: "♀",
    name: "优衣",
    option_name:"youyi",
    motto: "明天,好像会成为更强的自己!",
    tag: "种田梨沙",
    skill1_name:"花之灵息",
    skill1_des:"战斗开始时中幅度提升自己的魔攻",
    skill1_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/02/02/icon-1.png",
    skill2_name:"花之庇护",
    skill2_des:"小幅提升己方全体的物理防御力",
    skill2_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/02/02/icon-2.png",
    skill3_name:"花瓣射击",
    skill3_des:"对前方一名敌人造成魔法伤害(中)",
    skill3_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/02/02/icon-3.png",
    skill4_name:"全体治愈",
    skill4_des:"中幅回复己方全体生命力",
    skill4_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/02/02/icon-4.png",
    skill4_gif:"//static.biligame.com/pcr/gw/pc/images/p4/clan/02/02/4.gif",
}, {
    image:"https://img.moegirl.org/common/b/b4/Rei_prin_cone.png",
    race: "前卫",
    nature: "一星",
    sex: "♀",
    name: "怜",
    option_name:"ling",
    motto: "不断的努力是成长的秘诀哟",
    tag: "早见沙织",
    skill1_name:"迅捷剑姬",
    skill1_des:"战斗开始时中幅度提升自身物攻",
    skill1_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/02/03/icon-1.png",
    skill2_name:"反击斩",
    skill2_des:"对前方一名敌人造成物理伤害(中)。怜在攻击准备期间所受到的伤害越高,对敌人造成的伤害也会相应提高",
    skill2_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/02/03/icon-2.png",
    skill3_name:"狂风突刺",
    skill3_des:"对前方一名敌人造成物理伤害(中)",
    skill3_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/02/03/icon-3.png",
    skill4_name:"斩刃风暴",
    skill4_des:"对前方一名敌人造成物理伤害(特大)",
    skill4_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/02/03/icon-4.png",
    skill4_gif:"//static.biligame.com/pcr/gw/pc/images/p4/clan/02/03/4.gif",
}, {
    image:"https://img.moegirl.org/common/8/84/Shizuru_Hoshino.png",
    race: "前卫",
    nature: "三星",
    sex: "♀",
    name: "静流",
    option_name:"jingliu",
    motto: "姐姐会一直在你身边的噢!",
    tag: "生天目仁美",
    skill1_name:"姐姐的力量",
    skill1_des:"战斗开始时中幅度提升自己的物防",
    skill1_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/03/01/icon-1.png",
    skill2_name:"守护",
    skill2_des:"为自身周围的己方角色展开物理攻击无效化屏障",
    skill2_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/03/01/icon-2.png",
    skill3_name:"圣灵治愈",
    skill3_des:"中幅回复生命值最低的一名己方角色的生命值",
    skill3_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/03/01/icon-3.png",
    skill4_name:"神圣惩击",
    skill4_des:"对前方一名敌人造成物理伤害(大),并为自身展开物理吸收屏障",
    skill4_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/03/01/icon-4.png",
    skill4_gif:"//static.biligame.com/pcr/gw/pc/images/p4/clan/03/01/4.gif",
}, {
    image:"https://img.moegirl.org/common/8/81/Rino_prin_cone.png",
    race: "后卫",
    nature: "三星",
    sex: "♀",
    name: "璃乃",
    option_name:"linai",
    motto: "我要成为能够保护哥哥的最强的妹妹!",
    tag: "阿澄佳奈",
    skill1_name:"敏锐洞察",
    skill1_des:"战斗开始时中幅度提升自身物攻",
    skill1_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/03/02/icon-1.png",
    skill2_name:"突破之箭",
    skill2_des:"对前方一名敌人造成物理伤害(中)",
    skill2_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/03/02/icon-2.png",
    skill3_name:"全神贯注",
    skill3_des:"中幅提升自身物理攻击力和物理暴击率",
    skill3_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/03/02/icon-3.png",
    skill4_name:"箭矢之雨",
    skill4_des:"对前方范围内的所有敌人造成物理伤害(中)",
    skill4_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/03/02/icon-4.png",
    skill4_gif:"//static.biligame.com/pcr/gw/pc/images/p4/clan/03/02/4.gif",
}, {
    image:"https://img.moegirl.org/common/e/ef/Chika_prin_cone.png",
    race: "后卫",
    nature: "二星",
    sex: "♀",
    name: "千歌",
    option_name:"qiange",
    motto: "用我的歌声,为大家带来幸福!",
    tag: "福原绫香",
    skill1_name:"天籁之音",
    skill1_des:"战斗开始时中幅度提升自己的魔攻",
    skill1_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/04/01/icon-1.png",
    skill2_name:"精灵摇篮曲",
    skill2_des:"中幅降低前方一名敌人的物理攻击力",
    skill2_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/04/01/icon-2.png",
    skill3_name:"激励之歌",
    skill3_des:"以最前方的己方角色为中心,小幅提升范围内全体己方角色的物理攻击力",
    skill3_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/04/01/icon-3.png",
    skill4_name:"风灵气息",
    skill4_des:"【召唤】中幅回复千歌前方所有己方角色的生命值,并在最前方的己方角色身边召唤精灵",
    skill4_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/04/01/icon-4.png",
    skill4_gif:"//static.biligame.com/pcr/gw/pc/images/p4/clan/04/01/4.gif",
}, {
    image:"https://img.moegirl.org/common/c/c9/Nozomi_prin_cone.png",
    race: "前卫",
    nature: "三星",
    sex: "♀",
    name: "望",
    option_name:"wang",
    motto: "将全世界都变成自己的舞台吧!",
    tag: "日笠阳子",
    skill1_name:"光明微笑",
    skill1_des:"战斗开始时中幅度提升自己的物防",
    skill1_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/04/02/icon-1.png",
    skill2_name:"偶像声援",
    skill2_des:"小幅回复自身周圉所有己方角色的生命值",
    skill2_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/04/02/icon-2.png",
    skill3_name:"悦音斩击",
    skill3_des:"对前方范围内的所有敌人造成物理伤害(小),并使其眩晕",
    skill3_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/04/02/icon-3.png",
    skill4_name:"演出开始",
    skill4_des:"【挑衅】小幅提升己方全体的物理攻击力,中幅提升自身的物理与魔法防御力。再对敌方全体进行挑衅",
    skill4_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/04/02/icon-4.png",
    skill4_gif:"//static.biligame.com/pcr/gw/pc/images/p4/clan/04/02/4.gif",
}, {
    image:"https://img.moegirl.org/common/9/93/Mimi_prin_cone.png",
    race: "中卫",
    nature: "二星",
    sex: "♀",
    name: "美美",
    option_name:"meimei",
    motto: "美美要像小花一样茁壮成长!",
    tag: "日高里菜",
    skill1_name:"兔兔力量",
    skill1_des:"战斗开始时中幅度提升自己的物攻",
    skill1_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/05/01/icon-1.png",
    skill2_name:"兔兔应援",
    skill2_des:"小幅提升己方全体的物理攻击力",
    skill2_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/05/01/icon-2.png",
    skill3_name:"跳跳攻击",
    skill3_des:"对前方范围内的所有敌人造成物理伤害(小),并使其眩晕",
    skill3_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/05/01/icon-3.png",
    skill4_name:"兔兔斩击",
    skill4_des:"对前方一名敌人造成物理伤害(中)",
    skill4_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/05/01/icon-4.png",
    skill4_gif:"//static.biligame.com/pcr/gw/pc/images/p4/clan/05/01/4.gif",
}, {
    image:"https://img.moegirl.org/common/5/50/Misogi.png",
    race: "前卫",
    nature: "一星",
    sex: "♀",
    name: "未奏希",
    option_name:"weizouxi",
    motto: "我要变得更强,让哥哥大吃一惊!",
    tag: "诸星堇",
    skill1_name:"陷阱专家",
    skill1_des:"战斗开始时中幅度提升自身物防",
    skill1_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/05/02/icon-1.png",
    skill2_name:"水球投掷",
    skill2_des:"对物理攻击力最高的一名敌人造成物理伤害(小),并小幅降低其物理攻击力,同时小幅提升自身物理攻击力",
    skill2_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/05/02/icon-2.png",
    skill3_name:"墨水射击",
    skill3_des:"对距离自身第二近的一名敌人造成物理伤害(小),并施加黑暗状态",
    skill3_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/05/02/icon-3.png",
    skill4_name:"捣蛋炸弹",
    skill4_des:"以距离自身第二近的敌人为中心,对范围内的所有敌人造成物理伤害(中)",
    skill4_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/05/02/icon-4.png",
    skill4_gif:"//static.biligame.com/pcr/gw/pc/images/p4/clan/05/02/4.gif",
}, {
    image:"https://img.moegirl.org/common/9/91/Aoi_prin_cone.png",
    race: "后卫",
    nature: "一星",
    sex: "♀",
    name: "碧",
    option_name:"bi",
    motto: "孤独的力量,觉醒吧!",
    tag: "花泽香菜",
    skill1_name:"森林射手",
    skill1_des:"战斗开始时中幅度提升自己的物攻",
    skill1_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/06/01/icon-1.png",
    skill2_name:"麻痹箭矢",
    skill2_des:"对前方一名敌人造成物理伤害(小),并使其陷入麻痹状态",
    skill2_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/06/01/icon-2.png",
    skill3_name:"剧毒箭矢",
    skill3_des:"对前方一名敌人造成物理伤害(中),并使其陷入中毒状态",
    skill3_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/06/01/icon-3.png",
    skill4_name:"藤蔓旋舞",
    skill4_des:"以距离自身最近的一名敌人为中心,对范围内的敌人造成物理伤害(中)",
    skill4_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/06/01/icon-4.png",
    skill4_gif:"//static.biligame.com/pcr/gw/pc/images/p4/clan/06/01/4.gif",
}, {
    image:"https://img.moegirl.org/common/a/ad/Hatsune_prin_cone.png",
    race: "后卫",
    nature: "三星",
    sex: "♀",
    name: "初音",
    option_name:"chuyin",
    motto: "我可不是只会睡觉的噢!",
    tag: "大析彩香",
    skill1_name:"幸福☆能量",
    skill1_des:"战斗开始时中幅度提升自己的魔攻",
    skill1_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/06/02/icon-1.png",
    skill2_name:"炫目☆星光",
    skill2_des:"对物理攻击力最高的一名敌人造成魔法伤害(小),并施加晕眩效果",
    skill2_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/06/02/icon-2.png",
    skill3_name:"精神☆爆破",
    skill3_des:"对物理攻击力最高的一名敌人造成魔法伤害(中)",
    skill3_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/06/02/icon-3.png",
    skill4_name:"闪耀☆流星",
    skill4_des:"对使用物理攻击的所有敌人造成魔法伤害(小),并对敌方全体造成魔法伤害(中)",
    skill4_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/06/02/icon-4.png",
    skill4_gif:"//static.biligame.com/pcr/gw/pc/images/p4/clan/06/02/4.gif",
}, {
    image:"https://img.moegirl.org/common/1/16/Miyako_prin_cone.png",
    race: "前卫",
    nature: "二星",
    sex: "♀",
    name: "宫子",
    option_name:"gongzi",
    motto: "现在的宫子已经是布丁之神啦~!",
    tag: "雨宫天",
    skill1_name:"透明妖怪来咯",
    skill1_des:"战斗开始时中幅度提升自己的物攻",
    skill1_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/07/01/icon-1.png",
    skill2_name:"点心时间到了",
    skill2_des:"中幅回复自身生命值",
    skill2_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/07/01/icon-2.png",
    skill3_name:"我~好~恨~啊",
    skill3_des:"【变身】变身为幽灵,在一段时间内处于无敌状态",
    skill3_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/07/01/icon-3.png",
    skill4_name:"把你变成布丁",
    skill4_des:"对前方一名敌人造成物理伤害(大),并大幅回复自身生命值",
    skill4_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/07/01/icon-4.png",
    skill4_gif:"//static.biligame.com/pcr/gw/pc/images/p4/clan/07/01/4.gif",
},  {
    image:"https://img.moegirl.org/common/5/50/Yori_prin_cone.png",
    race: "中卫",
    nature: "一星",
    sex: "♀",
    name: "依里",
    option_name:"yili",
    motto: "现在的我就像是处于无敌模式一样!",
    tag: "原纱友里",
    skill1_name:"闪电爆发",
    skill1_des:"战斗开始时中幅度提升自己的魔攻",
    skill1_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/07/02/icon-1.png",
    skill2_name:"阴影爆破",
    skill2_des:"对前方范围内的所有敌人造成魔法伤害(中)",
    skill2_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/07/02/icon-2.png",
    skill3_name:"极限充能",
    skill3_des:"消耗生命值,大幅提升自身的魔法攻击力",
    skill3_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/07/02/icon-3.png",
    skill4_name:"闪电标枪",
    skill4_des:"对前方范围内的所有敌人造成魔法伤害(中)",
    skill4_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/07/02/icon-4.png",
    skill4_gif:"//static.biligame.com/pcr/gw/pc/images/p4/clan/07/02/4.gif",
}, {
    image:"https://img.moegirl.org/common/3/3a/Akari_prin_cone.png",
    race: "中卫",
    nature: "二星",
    sex: "♀",
    name: "茜里",
    option_name:"qianli",
    motto: "各方面都得到了成长呀!",
    tag: "浅仓杏美",
    skill1_name:"炙热甜蜜",
    skill1_des:"战斗开始时中幅度提升自己的魔攻",
    skill1_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/07/03/icon-1.png",
    skill2_name:"小恶魔之吻",
    skill2_des:"中幅降低前方一名敌人的魔法防御力",
    skill2_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/07/03/icon-2.png",
    skill3_name:"暗影伏特",
    skill3_des:"对前方一名敌人造成魔法伤害(中)",
    skill3_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/07/03/icon-3.png",
    skill4_name:"甜蜜恶魔声援",
    skill4_des:"小幅提升己方全体的魔法攻击力,并根据下次攻击的伤害量回复生命值",
    skill4_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/07/03/icon-4.png",
    skill4_gif:"//static.biligame.com/pcr/gw/pc/images/p4/clan/07/03/4.gif",
}, {
    image:"https://img.moegirl.org/common/b/bd/Shinobu_prin_cone.png",
    race: "中卫",
    nature: "二星",
    sex: "♀",
    name: "忍",
    option_name:"ren",
    motto: "这是以往都不曾达到的灵力强度",
    tag: "大坪由佳",
    skill1_name:"暗夜的镇魂曲",
    skill1_des:"战斗开始时中幅度提升自己的物攻",
    skill1_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/07/04/icon-1.png",
    skill2_name:"虚弱亡魂",
    skill2_des:"小幅降低敌方全体的物理防御力",
    skill2_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/07/04/icon-2.png",
    skill3_name:"亡灵召唤",
    skill3_des:"【召喚】在自身的前方召唤一个能够攻击前方一名敌人的骷髅",
    skill3_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/07/04/icon-3.png",
    skill4_name:"亡灵恐惧",
    skill4_des:"对前方范围内的所有敌人造成物理伤害(中),并小幅降低其物理防御力",
    skill4_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/07/04/icon-4.png",
    skill4_gif:"//static.biligame.com/pcr/gw/pc/images/p4/clan/07/04/4.gif",
}, {
    image:"https://img.moegirl.org/common/7/7a/Suzume_prin_cone.png",
    race: "后卫",
    nature: "一星",
    sex: "♀",
    name: "铃莓",
    option_name:"lingmei",
    motto: "我会作为女仆,把工作完美完成的!",
    tag: "悠木碧",
    skill1_name:"女仆精神",
    skill1_des:"战斗开始时中幅度提升自己的魔攻",
    skill1_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/08/01/icon-1.png",
    skill2_name:"女仆声援",
    skill2_des:"小幅回复自身周围的所有己方角色的生命值,并小幅提升其物理攻击力",
    skill2_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/08/01/icon-2.png",
    skill3_name:"旋风爆破",
    skill3_des:"对前方范围内的所有敌人造成魔法伤害(小)",
    skill3_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/08/01/icon-3.png",
    skill4_name:"旋风气流",
    skill4_des:"对前方范围内的所有敌人造成魔法伤害(中),并小~中幅降低其物理防御力",
    skill4_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/08/01/icon-4.png",
    skill4_gif:"//static.biligame.com/pcr/gw/pc/images/p4/clan/08/01/4.gif",
}, {
    image:"https://img.moegirl.org/common/6/68/Saren_prin_cone.png",
    race: "中卫",
    nature: "三星",
    sex: "♀",
    name: "咲恋",
    option_name:"xiaolian",
    motto: "来吧大家,跟上我!",
    tag: "堀江由衣",
    skill1_name:"优雅高贵之魂",
    skill1_des:"战斗开始时中幅度提升自己的物攻",
    skill1_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/08/02/icon-1.png",
    skill2_name:"优雅声援",
    skill2_des:"中幅回复一名距离自身最近的己方角色的技能值",
    skill2_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/08/02/icon-2.png",
    skill3_name:"烈焰斩击",
    skill3_des:"对前方范围内的所有敌人造成物理伤害(小)",
    skill3_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/08/02/icon-3.png",
    skill4_name:"凤凰之剑",
    skill4_des:"对前方范围内的所有敌人造成物理伤害(中)。咲恋的生命值越低,给予的伤害则越高",
    skill4_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/08/02/icon-4.png",
    skill4_gif:"//static.biligame.com/pcr/gw/pc/images/p4/clan/08/02/4.gif",
}, {
    image:"https://img.moegirl.org/common/e/ec/Kurumi_prin_cone.png",
    race: "前卫",
    nature: "一星",
    sex: "♀",
    name: "胡桃",
    option_name:"hutao",
    motto: "虽然很可怕…但我已经,已经不会再逃避了!",
    tag: "植田佳奈",
    skill1_name:"光辉之力",
    skill1_des:"战斗开始时中幅度提升自身生命值上限",
    skill1_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/08/03/icon-1.png",
    skill2_name:"战栗之铃",
    skill2_des:"对前方一名敌人造成物理伤害(小),并使其眩晕",
    skill2_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/08/03/icon-2.png",
    skill3_name:"勇敢之铃",
    skill3_des:"小幅提升自身周围的己方角色的物理防御力和魔法防御力",
    skill3_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/08/03/icon-3.png",
    skill4_name:"惊吓挥铃",
    skill4_des:"对前方一名敌人造成物理伤害(大),并使其长时间眩晕",
    skill4_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/08/03/icon-4.png",
    skill4_gif:"//static.biligame.com/pcr/gw/pc/images/p4/clan/08/03/4.gif",
}, {
    image:"https://img.moegirl.org/common/8/8c/Makoto_prin_cone.png",
    race: "前卫",
    nature: "三星",
    sex: "♀",
    name: "真琴",
    option_name:"zhenqing",
    motto: "感觉已经不会输给任何人了!",
    tag: "小松未可子",
    skill1_name:"狼牙的猛击",
    skill1_des:"战斗开始时中幅度提升自己的物攻",
    skill1_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/09/01/icon-1.png",
    skill2_name:"勇气呐喊",
    skill2_des:"中幅降低前方一名敌人的物理防御力",
    skill2_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/09/01/icon-2.png",
    skill3_name:"强力斩击",
    skill3_des:"对前方一名敌人造成物理伤害(中)",
    skill3_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/09/01/icon-3.png",
    skill4_name:"天狼噬斩",
    skill4_des:"对前方一名敌人造成物理伤害(大),并中幅降低其物理防御力",
    skill4_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/09/01/icon-4.png",
    skill4_gif:"//static.biligame.com/pcr/gw/pc/images/p4/clan/09/01/4.gif",
}, {
    image:"https://img.moegirl.org/common/2/2c/Mahou_prin_cone.png",
    race: "后卫",
    nature: "三星",
    sex: "♀",
    name: "真步",
    option_name:"zhenbu",
    motto: "人家的力量,正在不断增强呢~",
    tag: "内田真礼",
    skill1_name:"童话充能",
    skill1_des:"战斗开始时中幅度提升自己的物防",
    skill1_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/09/02/icon-1.png",
    skill2_name:"真步真步致盲术",
    skill2_des:"使前方第二位的敌人陷入黑暗状态",
    skill2_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/09/02/icon-2.png",
    skill3_name:"真步真步治愈术",
    skill3_des:"中幅回复己方生命值最低的一名角色的生命值",
    skill3_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/09/02/icon-3.png",
    skill4_name:"童话庭院",
    skill4_des:"小幅提升己方全体的魔法攻击力、物理防御力,并小幅回复技能值",
    skill4_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/09/02/icon-4.png",
    skill4_gif:"//static.biligame.com/pcr/gw/pc/images/p4/clan/09/02/4.gif",
}, {
    image:"https://img.moegirl.org/common/9/95/Kaori_prin_cone.png",
    race: "前卫",
    nature: "二星",
    sex: "♀",
    name: "香织",
    option_name:"xiangzhi",
    motto: "界限什么的,一拳打破就好啦~!",
    tag: "高森奈津美",
    skill1_name:"正中线突破",
    skill1_des:"对前方一名敌人造成物理伤害(中)",
    skill1_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/09/03/icon-1.png",
    skill2_name:"精神统一",
    skill2_des:"技能发动后,每当香织对敌人进行攻击,该敌人所受的伤害量便会提升。此效果最多叠加5次",
    skill2_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/09/03/icon-2.png",
    skill3_name:"琉球犬式炼气术",
    skill3_des:"战斗开始时中幅度提升自己的物攻",
    skill3_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/09/03/icon-3.png",
    skill4_name:"琉球犬重拳出击",
    skill4_des:"对前方一名敌人造成物理伤害(特大)",
    skill4_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/09/03/icon-4.png",
    skill4_gif:"//static.biligame.com/pcr/gw/pc/images/p4/clan/09/03/4.gif",
}, {
    image:"https://img.moegirl.org/common/0/0a/Mahiru_prin_cone.png",
    race: "中卫",
    nature: "二星",
    sex: "♀",
    name: "真阳",
    option_name:"zhenyang",
    motto: "老哥和我一起将笑声传达到全世界吧~!",
    tag: "新田惠海",
    skill1_name:"必笑的段子",
    skill1_des:"战斗开始时,中幅提升自身物理攻击力",
    skill1_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/10/01/icon-1.png",
    skill2_name:"草叉斩击",
    skill2_des:"对前方一名敌人造成物理伤害(中),并小幅提升自身的物理攻击力",
    skill2_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/10/01/icon-2.png",
    skill3_name:"牛奶罐轰炸",
    skill3_des:"对前方一名敌人造成物理伤害(小),井将其小幅度吹飞",
    skill3_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/10/01/icon-3.png",
    skill4_name:"来吧!伊丽莎白",
    skill4_des:"对前方一名敌人造成物理伤害(大),并使其眩晕",
    skill4_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/10/01/icon-4.png",
    skill4_gif:"//static.biligame.com/pcr/gw/pc/images/p4/clan/10/01/4.gif",
}, {
    image:"https://img.moegirl.org/common/1/1a/Rima_prin_cone.png",
    race: "前卫",
    nature: "一星",
    sex: "♀",
    name: "莉玛",
    option_name:"lima",
    motto: "恋爱中的少女是无敌的!",
    tag: "德井青空",
    skill1_name:"防御毛皮",
    skill1_des:"战斗开始时中幅度提升自己的物防",
    skill1_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/10/02/icon-1.png",
    skill2_name:"毛茸茸头槌",
    skill2_des:"对前方一名敌人造成物理伤害(小),并使其眩晕",
    skill2_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/10/02/icon-2.png",
    skill3_name:"毛茸茸突击",
    skill3_des:"战斗开始片刻后,向最前方的敌人发起突击,对其造成物理伤害(中),并小幅提升自身物理防御力",
    skill3_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/10/02/icon-3.png",
    skill4_name:"毛茸茸挥击",
    skill4_des:"对前方范围内的所有敌人造成物理伤害(中),并大幅提升自身的物理防御力",
    skill4_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/10/02/icon-4.png",
    skill4_gif:"//static.biligame.com/pcr/gw/pc/images/p4/clan/10/02/4.gif",
}, {
    image:"https://img.moegirl.org/common/3/30/Shiori_prin_cone.png",
    race: "后卫",
    nature: "二星",
    sex: "♀",
    name: "栞",
    option_name:"kan",
    motto: "以前都不曾想过…身体竟然可以变得这么轻盈",
    tag: "小清水亚美",
    skill1_name:"瞄准强化",
    skill1_des:"战斗开始时中幅度提升自己的物攻",
    skill1_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/10/03/icon-1.png",
    skill2_name:"风之箭矢",
    skill2_des:"对前方一名敌人造成物理伤害(中),并小幅回复自身技能值",
    skill2_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/10/03/icon-2.png",
    skill3_name:"三重箭矢",
    skill3_des:"对前方的敌人(最多三名)造成物理伤害(小),并小幅回复身技能值",
    skill3_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/10/03/icon-3.png",
    skill4_name:"附魔箭矢",
    skill4_des:"对前方一名敌人造成物理伤害(大),并大幅度提升自身物理攻击力",
    skill4_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/10/03/icon-4.png",
    skill4_gif:"//static.biligame.com/pcr/gw/pc/images/p4/clan/10/03/4.gif",
}, {
    image:"https://img.moegirl.org/common/d/d7/Mifuyu.png",
    race: "中卫",
    nature: "二星",
    sex: "♀",
    name: "美冬",
    option_name:"meidong",
    motto: "不管是怎样的特卖,我都不会输的!",
    tag: "田所梓",
    skill1_name:"佣兵之傲",
    skill1_des:"战斗开始时中幅度提升自己的物攻",
    skill1_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/11/01/icon-1.png",
    skill2_name:"水流斩击",
    skill2_des:"对前方一名敌人造成物理伤害(小),并使其眩晕",
    skill2_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/11/01/icon-2.png",
    skill3_name:"急救术",
    skill3_des:"大幅回复自身的生命值",
    skill3_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/11/01/icon-3.png",
    skill4_name:"飞跃枪闪",
    skill4_des:"对前方一名敌人造成物理伤害(大),并使其眩晕",
    skill4_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/11/01/icon-4.png",
    skill4_gif:"//static.biligame.com/pcr/gw/pc/images/p4/clan/11/01/4.gif",
}, {
    image:"https://img.moegirl.org/common/2/2c/Akino_prin_cone.png",
    race: "前卫",
    nature: "三星",
    sex: "♀",
    name: "秋乃",
    option_name:"qiunai",
    motto: "跟我在一起的话,我会承诺你一个美好未来的哟!",
    tag: "松嵜丽",
    skill1_name:"灼热灵魂",
    skill1_des:"战斗开始时中幅度提升自己的物攻",
    skill1_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/11/02/icon-1.png",
    skill2_name:"治愈宝石",
    skill2_des:"在自身周围展开治疗领域,可小幅回复范围内所有己方角色的生命值",
    skill2_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/11/02/icon-2.png",
    skill3_name:"荣耀斩击",
    skill3_des:"对前方一名敌人造成物理伤害(中),并小幅提升自身的物理攻击力。若在大笑期间受到攻击,则会对范围内的敌人进行反击",
    skill3_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/11/02/icon-3.png",
    skill4_name:"高贵突击",
    skill4_des:"对前方一名敌人造成物理伤害(特大)",
    skill4_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/11/02/icon-4.png",
    skill4_gif:"//static.biligame.com/pcr/gw/pc/images/p4/clan/11/02/4.gif",
}, {
    image:"https://img.moegirl.org/common/e/e1/Tamaki_prin_cone.png",
    race: "前卫",
    nature: "二星",
    sex: "♀",
    name: "珠希",
    option_name:"zhuxi",
    motto: "现在的我,是猫中之王喵!",
    tag: "沼仓爱美",
    skill1_name:"绝妙猫咪",
    skill1_des:"战斗开始时中幅度提升自己的物攻",
    skill1_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/11/03/icon-1.png",
    skill2_name:"猫猫投掷",
    skill2_des:"对魔法攻击力最高的一名敌人造成物理伤害(中),并小幅降低其魔法攻击力",
    skill2_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/11/03/icon-2.png",
    skill3_name:"猫猫的随心所欲",
    skill3_des:"小幅降低魔法攻击力最高的一名敌人的技能值,并小幅回复自身技能值",
    skill3_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/11/03/icon-3.png",
    skill4_name:"猫猫决胜爪",
    skill4_des:"对魔攻最高的敌人造成特大幅度的物理伤害",
    skill4_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/11/03/icon-4.png",
    skill4_gif:"//static.biligame.com/pcr/gw/pc/images/p4/clan/11/03/4.gif",
}, {
    image:"https://img.moegirl.org/common/a/a4/Yukari_prin_cone.png",
    race: "中卫",
    nature: "一星",
    sex: "♀",
    name: "由加莉",
    option_name:"youjiali",
    motto: "就算是自己原本的样子,也要发光给你看!",
    tag: "今井麻美",
    skill1_name:"序曲泡泡饮",
    skill1_des:"战斗开始时中幅度提升自己的魔防",
    skill1_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/11/04/icon-1.png",
    skill2_name:"月下独酌",
    skill2_des:"中幅回复技能值最低的一名己方角色的技能值",
    skill2_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/11/04/icon-2.png",
    skill3_name:"生命之水",
    skill3_des:"中幅回复生命值最低的一名己方角色的生命值",
    skill3_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/11/04/icon-3.png",
    skill4_name:"七重纱护",
    skill4_des:"为己方全体展开魔法攻击无效化屏障",
    skill4_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/11/04/icon-4.png",
    skill4_gif:"//static.biligame.com/pcr/gw/pc/images/p4/clan/11/04/4.gif",
}, {
    image:"https://img.moegirl.org/common/0/0c/Eriko_prin_cone.png",
    race: "前卫",
    nature: "二星",
    sex: "♀",
    name: "惠理子",
    option_name:"huilizi",
    motto: "就算是自己原本的样子,也要发光给你看!",
    tag: "桥本千波",
    skill1_name:"狂爱之力",
    skill1_des:"战斗开始时中幅度提升自己的物攻",
    skill1_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/12/01/icon-1.png",
    skill2_name:"剧毒打击",
    skill2_des:"对前方一名敌人造成物理伤害(中),并使其陷入中毒状态",
    skill2_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/12/01/icon-2.png",
    skill3_name:"痴迷执念",
    skill3_des:"小幅提升自身的物理攻击力",
    skill3_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/12/01/icon-3.png",
    skill4_name:"致命惩罚",
    skill4_des:"对前方一名敌人造成物理伤害(特大),使用该技能打倒敌人时,大幅提升自身物理攻击力",
    skill4_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/12/01/icon-4.png",
    skill4_gif:"//static.biligame.com/pcr/gw/pc/images/p4/clan/12/01/4.gif",
}, {
    image:"https://img.moegirl.org/common/3/34/Anna_prin_cone.png",
    race: "中卫",
    nature: "三星",
    sex: "♀",
    name: "杏奈",
    option_name:"xinnai",
    motto: "唔!魔瞳在颤抖…!时刻已到了吗…!",
    tag: "高野麻美",
    skill1_name:"霸叉冥灭狱炎咒",
    skill1_des:"战斗开始时中幅度提升自己的魔攻",
    skill1_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/12/02/icon-1.png",
    skill2_name:"冥空天升",
    skill2_des:"【自爆】当杏奈的生命值低于最大生命值的10发动,对周边所有敌人造成魔法伤害(大),但自身会陷入无法战斗状态",
    skill2_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/12/02/icon-2.png",
    skill3_name:"罗刹涅槃·无式",
    skill3_des:"对前方一名敌人造成魔法伤害(中)",
    skill3_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/12/02/icon-3.png",
    skill4_name:"罗刹涅槃·极光终天冥坏破",
    skill4_des:"对敌方全体造成魔法伤害(中),使用后杏奈的物理与魔法防御力会特大幅降低",
    skill4_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/12/02/icon-4.png",
    skill4_gif:"//static.biligame.com/pcr/gw/pc/images/p4/clan/12/02/4.gif",
}, {
    image:"https://img.moegirl.org/common/f/f0/Mitsuki_prin_cone.png",
    race: "中卫",
    nature: "二星",
    sex: "♀",
    name: "深月",
    option_name:"shenyue",
    motto: "这是科学进步的一步…对吧",
    tag: "三石琴乃",
    skill1_name:"独眼的恶魔",
    skill1_des:"战斗开始时中幅度提升自己的物攻",
    skill1_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/12/03/icon-1.png",
    skill2_name:"蔷薇领域",
    skill2_des:"使前方范围内的所有敌人陷入诅咒状态",
    skill2_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/12/03/icon-2.png",
    skill3_name:"诅咒绽放",
    skill3_des:"在自身前方一定范围内展开能大幅降低物理防御力的领域",
    skill3_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/12/03/icon-3.png",
    skill4_name:"血色蔷薇",
    skill4_des:"对前方范围内的所有敌人造成物理伤害(中)。根据被该技能打倒的敌人数量,回复自身生命值",
    skill4_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/12/03/icon-4.png",
    skill4_gif:"//static.biligame.com/pcr/gw/pc/images/p4/clan/12/03/4.gif",
}, {
    image:"https://img.moegirl.org/common/d/d6/Misaki_prin_cone.png",
    race: "后卫",
    nature: "一星",
    sex: "♀",
    name: "美咲",
    option_name:"meixiao",
    motto: "这样成熟的我也让你完全沉迷了吧!",
    tag: "久野美咲",
    skill1_name:"淑女的修养",
    skill1_des:"战斗开始时,中幅提升自身魔法攻击力",
    skill1_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/13/01/icon-1.png",
    skill2_name:"减速之眼",
    skill2_des:"对范围内所有敌人造成3次魔法伤害(小)。以距离美咲最近的敌人为范围中心",
    skill2_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/13/01/icon-2.png",
    skill3_name:"黑暗粒子",
    skill3_des:"对前方一名敌人造成魔法伤害(小),并小幅降低其行动速度",
    skill3_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/13/01/icon-3.png",
    skill4_name:"毁灭之眼",
    skill4_des:"对前方所有敌人造成魔法伤害(中)",
    skill4_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/13/01/icon-4.png",
    skill4_gif:"//static.biligame.com/pcr/gw/pc/images/p4/clan/13/01/4.gif",
},  {
    image:"https://img.moegirl.org/common/d/da/Io_prin_cone.png",
    race: "后卫",
    nature: "三星",
    sex: "♀",
    name: "伊绪",
    option_name:"yixu",
    motto: "老师的身体里,不断有力量在迸发呢…!",
    tag: "伊藤静",
    skill1_name:"可爱甜心",
    skill1_des:"战斗开始时中幅度提升自己的魔攻",
    skill1_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/13/02/icon-1.png",
    skill2_name:"灵魂抽取",
    skill2_des:"小幅降低随机一名敌人的技能值,并小幅回复自身技能值",
    skill2_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/13/02/icon-2.png",
    skill3_name:"夺魂尾鞭",
    skill3_des:"对前方范围内的所有敌人造成魔法伤害(小)",
    skill3_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/13/02/icon-3.png",
    skill4_name:"百魅惑心",
    skill4_des:"对敌方全体造成魔法伤害(小),并使其陷入魅惑状态",
    skill4_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/13/02/icon-4.png",
    skill4_gif:"//static.biligame.com/pcr/gw/pc/images/p4/clan/13/02/4.gif",
}, {
    image:"https://img.moegirl.org/common/3/3e/Suzuna.png",
    race: "后卫",
    nature: "二星",
    sex: "♀",
    name: "玲奈",
    option_name:"lingnai",
    motto: "像是超级可爱之上还有超级强大~,这样",
    tag: "上坂堇",
    skill1_name:"可爱感觉",
    skill1_des:"战斗开始时中幅度提升自己的物攻",
    skill1_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/13/03/icon-1.png",
    skill2_name:"魅力全开",
    skill2_des:"中幅提升自身物理攻击力",
    skill2_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/13/03/icon-2.png",
    skill3_name:"愤怒之镖",
    skill3_des:"对前方一名敌人造成物理伤害(中)。此技能必定暴击",
    skill3_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/13/03/icon-3.png",
    skill4_name:"一箭穿心",
    skill4_des:"对前方一名敌人造成物理伤害(大)。此技能必定暴击",
    skill4_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/13/03/icon-4.png",
    skill4_gif:"//static.biligame.com/pcr/gw/pc/images/p4/clan/13/03/4.gif",
}, {
    image:"https://img.moegirl.org/common/3/3f/Ninon_jubeeru.png",
    race: "中卫",
    nature: "三星",
    sex: "♀",
    name: "妮侬",
    option_name:"ninong",
    motto: "与将军一起一统天下!",
    tag: "佐藤聪美",
    skill1_name:"本能寺之助",
    skill1_des:"战斗开始时中幅度提升自己的物攻",
    skill1_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/14/01/icon-1.png",
    skill2_name:"火炎扇",
    skill2_des:"对前方一名敌人造成物理伤害(中),并将其小幅度击飞",
    skill2_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/14/01/icon-2.png",
    skill3_name:"旋风击",
    skill3_des:"对前方范围内的所有敌人造成物理伤害(小),使用该技能打倒敌人时,中幅回复自身技能值",
    skill3_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/14/01/icon-3.png",
    skill4_name:"忍法灼热地狱",
    skill4_des:"对前方范围内的所有敌人造成物理伤害(中)",
    skill4_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/14/01/icon-4.png",
    skill4_gif:"//static.biligame.com/pcr/gw/pc/images/p4/clan/14/01/4.gif",
}, {
    image:"https://img.moegirl.org/common/5/57/Kuuka_prin_cone.png",
    race: "前卫",
    nature: "二星",
    sex: "♀",
    name: "空花",
    option_name:"konghua",
    motto: "身体…身体已经到极限了!",
    tag: "长妻树里",
    skill1_name:"妄想守护",
    skill1_des:"战斗开始时中幅度提升自己的魔防",
    skill1_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/14/02/icon-1.png",
    skill2_name:"激烈的都来者不拒!",
    skill2_des:"中幅提升自身的魔法防御力",
    skill2_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/14/02/icon-2.png",
    skill3_name:"冲着空花来吧!",
    skill3_des:"【挑衅】挑衅敌方全体,并小幅提升自身的物理防御力",
    skill3_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/14/02/icon-3.png",
    skill4_name:"神魂颠倒",
    skill4_des:"为自身展开魔法吸收屏障,并中幅回复生命值",
    skill4_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/14/02/icon-4.png",
    skill4_gif:"//static.biligame.com/pcr/gw/pc/images/p4/clan/14/02/4.gif",
}, {
    image:"https://img.moegirl.org/common/7/7b/Monika_wuaisuwuinto.png",
    race: "中卫",
    nature: "三星",
    sex: "♀",
    name: "莫妮卡",
    option_name:"monika",
    motto: "拜斯温特无人能敌!",
    tag: "辻步美",
    skill1_name:"白翼的加护",
    skill1_des:"战斗开始时中幅度提升自己的物攻",
    skill1_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/14/03/icon-1.png",
    skill2_name:"火枪射击!",
    skill2_des:"对前方一名敌人造成物理伤害(中),并使其眩晕",
    skill2_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/14/03/icon-2.png",
    skill3_name:"白翼鼓舞!",
    skill3_des:"小幅提升己方全体的物理、魔法攻击力,并小幅提升行动速度",
    skill3_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/14/03/icon-3.png",
    skill4_name:"紫电一闪",
    skill4_des:"对前方范围内的所有敌人造成物理伤害(大)",
    skill4_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/14/03/icon-4.png",
    skill4_gif:"//static.biligame.com/pcr/gw/pc/images/p4/clan/14/03/4.gif",
},  {
    image:"https://img.moegirl.org/common/3/3a/Yuki_prin_cone.png",
    race: "后卫",
    nature: "二星",
    sex: "♀",
    name: "雪",
    option_name:"xue",
    motto: "我的美丽,已经与神灵并驾了吧!",
    tag: "大空直美",
    skill1_name:"可爱的我会努力哦",
    skill1_des:"战斗开始时中幅度提升自己的魔攻",
    skill1_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/14/04/icon-1.png",
    skill2_name:"可爱的我会为你加油的",
    skill2_des:"中幅回复己方技能值最高的一名角色的技能值",
    skill2_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/14/04/icon-2.png",
    skill3_name:"我那令人目眩的美貌",
    skill3_des:"对距离自身第二近的一名敌人造成魔法伤害(小),并施加黑暗状态",
    skill3_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/14/04/icon-3.png",
    skill4_name:"拜倒在我的美貌之下吧",
    skill4_des:"对前方所有敌人造成魔法伤害(小),并小幅降低其物理防御力",
    skill4_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/14/04/icon-4.png",
    skill4_gif:"//static.biligame.com/pcr/gw/pc/images/p4/clan/14/04/4.gif",
}, {
    image:"https://img.moegirl.org/common/7/7c/Juuta.png",
    race: "前卫",
    nature: "三星",
    sex: "♀",
    name: "姬塔",
    option_name:"jita",
    motto: "青空在…呼唤着我!",
    tag: "金元寿子",
    skill1_name:"龙卷的攻刃",
    skill1_des:"战斗开始时,中幅提升自身物理攻击力",
    skill1_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/15/01/icon-1.png",
    skill2_name:"剑意迸发",
    skill2_des:"中幅回复自身技能值",
    skill2_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/15/01/icon-2.png",
    skill3_name:"广域斩击",
    skill3_des:"对前方一名敌人造成物理伤害(中)",
    skill3_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/15/01/icon-3.png",
    skill4_name:"疾风剑雨",
    skill4_des:"对前方一名敌人造成物理伤害(特大)",
    skill4_image:"//static.biligame.com/pcr/gw/pc/images/p4/clan/15/01/icon-4.png",
    skill4_gif:"//static.biligame.com/pcr/gw/pc/images/p4/clan/15/01/4.gif",
}];
